# Generated by Django 3.2.9 on 2021-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('B', 'BOOK'), ('V', 'VIDEO'), ('P', 'PDF')], max_length=100),
        ),
    ]
