# Generated by Django 3.2.9 on 2021-12-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(default='material', max_length=200),
        ),
    ]
