# Generated by Django 4.0.1 on 2022-02-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resource_tags'),
    ]

    operations = [
    ]
